# -*- coding: utf-8 -*-
"""Linear_Regression_Model.ipynb
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/github/balqeesbegum01/AI-student-package-predictor/blob/main/linear_regression_model.py
"""
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model   import LinearRegression
#loading data
data=pd.read_csv("cgpa.csv")
print(data)
#check null
print(data.isnull().sum())
#define X and Y
x=data.iloc[:,[-2]].values
y=data.iloc[:,[-1]].values
print(x.shape,y.shape)
#split the data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(x_train,x_test,y_train,y_test)
#define model
lr=LinearRegression()
lr.fit(x_train,y_train)
#test the model
y_pred=lr.predict(x_test)
print(y_pred)
print(y_pred.shape)
#find the accuracy of train and test
trainaccuracy=lr.score(x_train,y_train)
testaccuracy=lr.score(x_test,y_test)
print(trainaccuracy)
print(testaccuracy)
from sklearn.metrics import mean_squared_error
msc=mean_squared_error(y_test,y_pred)
print(msc)
rmse=np.sqrt(msc)
print(rmse)
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
y_pred = lr.predict(x_test)
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))
y_test
y_pred
cgpa=float(input("Enter your CGPA:"))
package=lr.predict([[cgpa]])
print("CGPA:",cgpa)
print("predicted package:",package[0][0],"LPA")
import streamlit as st
st.title("My Linear Regression App")
x = st.number_input("Enter your CGPA")
if st.button("Click"):
    st.write("You entered:", x)
